### ISSUE TITLE
Trying to stop the tour will put it in a loop

### ISSUE THREAD

**Issue by pcm0nk** [pulsardev/vue-tour#102]
Hi,
Im trying to stop the tour after its 3rd step using the code below on my nextStep custom callback
```javascript
 myCustomNextStepCallback (currentStep) {
    if (currentStep ===3) {
       this.$tours.myTour.stop()
    }
  }
```
unfortunately it goes into a loop and it starts the tour from step 1 to the stop I called the `stop()` and it wont get closed untill I press the `Skip` button or press `Esc` key
So How can I stop my tour ,Also I dont like to use v-if as its not good practice.
Thanks in Advanced

**Comment by Darkzarich** [comment]
I met the same issue today, what I did was maybe not right but it worked, kind of a hack:

```
 myCustomNextStepCallback (currentStep) {
    if (currentStep === 3 && !this.$tours.myTour.steps[currentStep].finished) {
       this.$tours.myTour.steps[currentStep].finished  = true; // we cat set custom variables as we please
       this.$tours.myTour.stop()
    }
  }
```

**Comment by mmorainville** [comment]
Hi,

You may have messed something up with the index of the current step as the currentStep property of VTour is editable using the `$tours` property.
Essentially what the `stop` method does is just set the currentStep to `-1` and remove the active class:

```js
stop () {
  this.customCallbacks.onStop()
  document.body.classList.remove('v-tour--active')
  this.currentStep = -1
}
```

Anyway the problem seems linked to your code rather than vue-tour so I'm closing this issue. Feel free to reopen it if needed.
