### ISSUE TITLE
The computed property "skip" is already defined as a prop.

### ISSUE THREAD

**Issue by jofftiquez** [pulsardev/vue-tour#116]
The computed property "skip" is already defined as a prop in `v1.3.0`

**Comment by glorat** [comment]
It's a `prop` on the VStep and a `method` on the VTour so no conflict there. I don't see and `computed` property called `skip`.

**Comment by jofftiquez** [comment]
Why did you close the issue? This is clearly an error caused by v-tour.

**Comment by mmorainville** [comment]
Hi @jofftiquez,

Sorry for closing this quickly, but it's exactly as @glorat says, `skip` is defined only once in VStep and once in VTour, there is no reason there could be a conflict here.
Can you elaborate and/or give us an example of the problem please?

**Comment by jofftiquez** [comment]
Thanks @mmorainville. To give more light to the problem here: 

```vue
  v-tour(
      name="tourMain"
      :steps="tourStepsMain"
      :callbacks="tourCallbacksMain"
    )
```

Above is the only implementation I have in my app. The error appears whenever I press "Skip Tour" or "Finish".

**Comment by mmorainville** [comment]
We don't reproduce the problem with a fresh install, do you have somewhere in your code a computed named `skip`?
How does your `tourCallbacksMain` variable look like?
Are you able to reproduce the issue in a Codepen or some other playground?

**Comment by glorat** [comment]
I'm going to take a wild guess here... if the error is really 
`The computed property "skip" is already defined as a prop`
then it is almost certainly a bug in the client code because there simply is not computed property "skip" in this codebase so it should be somewhere else

In order to avoid wild guessing, a codepen or something would be needed. @mmorainville can you do that?

@jofftiquez and other repo owners - I'd recommend setting up an issue template for this project to mitigate such issues

**Comment by mmorainville** [comment]
Indeed @glorat a starter vue-tour codepen would be great. I can't do it right now, but we'll definitely set up one to make reproducing issues easier.
And yes an issue template would be great, we'll work on that too.

**Comment by mmorainville** [comment]
Here you go for the Codepen: https://codepen.io/Eligius/pen/wvMXrVY.
I'll now close this issue as the problem seems to be invalid.
