### ISSUE TITLE
Support for showing (and dismissing) multiple tooltips at once.

### ISSUE THREAD

**Issue by tamaccount** [pulsardev/vue-tour#123]
Hi. 

Is there any way currently to show multiple tooltips at once, instead of in the 1-step-at-a-time fashion?
(So, for clarification, I am asking if, for example, we could show 3 tooltips all at once on the page instead of showing them each to the user, one after the other.)

If not, can support be added for this capability?

Thank you.

**Comment by mmorainville** [comment]
Hi @tamaccount,

It's an interesting use case... It shouldn't be that hard to implement, but depending on how it's done it could impact a lot of things.
I don't think we'll implement it in vue-tour, as we want to keep it simple, but if you really need this functionality, here are some suggestions/guidelines.

First, you should convert the `currentStep` variable (https://github.com/pulsardev/vue-tour/blob/master/src/components/VTour.vue#L69) to an array.
Then, you should also change the condition to display the step: https://github.com/pulsardev/vue-tour/blob/master/src/components/VTour.vue#L20 so that it tests the existence of the step for each currentStep's values.

Also, if you don't want to code or bother at all, you could always start multiple tours simultaneously and synchronize their respective currentStep.

Hope it helps!
