### ISSUE TITLE
How to smooth scroll on iPhone?

### ISSUE THREAD

**Issue by DenniLa2** [pulsardev/vue-tour#129]
On iPhone (safari and chrome) page momentally scrolled: https://www.amazon.com/clouddrive/share/Ba5mVifCuVtxvDu3LKtSViKNpq4LE8jugYWC9i66sCr
How to fix this?

**Comment by HZooly** [comment]
@DenniLa2 Indeed smooth scroll seems to be not working on Safari iOS, we will investigate this issue, thanks for submitting.

**Comment by HZooly** [comment]
Safari doesn't support option we use in `scrollIntoView` function.
https://developer.mozilla.org/fr/docs/Web/API/Element/scrollIntoView

I don't know if we can help at the library level.

**Comment by HZooly** [comment]
@DenniLa2 can you please share your source code with us?

**Comment by mmorainville** [comment]
Hi @DenniLa2,

As @HZooly said `scrollIntoView` seems to be the issue.
But there should be a workaround for it, as we also use a scrolling library when scrolling is enabled.

As you can you see in the code of `VStep.vue`:

```
    enableScrolling () {
      if (this.params.enableScrolling) {
        if (this.step.duration || this.step.offset) {
          let jumpOptions = {
            duration: this.step.duration || 1000,
            offset: this.step.offset || 0,
            callback: undefined,
            a11y: false
          }
          jump(this.targetElement, jumpOptions)
        } else {
          // Use the native scroll by default if no scroll options has been defined
          this.targetElement.scrollIntoView({ behavior: 'smooth' })
        }
      }
    }
```

We only use the native scrolling if no scroll options has been defined.
So you should try to enable scrolling **and** adding a custom duration so that you enter the block which uses the scroll library (`jump.js`).

Hope this helps!
