### ISSUE TITLE
Manually Trigger next step and prev step?

### ISSUE THREAD

**Issue by emjimadhu** [pulsardev/vue-tour#16]
First of all, thank you so much for this beautiful component. It's exactly what i needed. But i have few questions. 

1) How can we turn off automatic next step and prev step events? 
i want to stop user to stay in current step until he/she finishes some task and after that he/she can go to next step. I used callback methods. But it just giving me indication, that user clicked next/prev button and proceeds with next/prev step. what i want is i dont want the user to go to next step. i can trigger it manually.

EDIT: i looked into this issue #12 . it seems in my vue methods i get `myTour of undefined`. i have excatly the same name as in the example.

2) I followed this #3 to get the current index to highlight the current step block. but the problem is, when i reload i get `currentStep is undefined`. i dont know what i am doing wrong. 

3) How can i reference a remote component?
Say i have a navigation bar. i included it in app.vue and now i am in some route. after user finished the current steps. i want to let user know that he/she can go to "particular" page to continue.

i already searched issues and docs for these issues. but couldnt find one.

thanks in advance.

**Comment by mmorainville** [comment]
Hi @emjimadhu,

You raised some interesting points. Nearly everything can be accomplished by customizing the template though and stopping the automatic next and previous step events is one of them.

You can take a look at this [part](https://pulsar.gitbooks.io/vue-tour/customizing-the-template.html) of the doc and https://github.com/pulsardev/vue-tour/issues/12 was indeed the right issue to look at.

Now your problem about `myTour of undefined` seems to come from a wrong usage of the plugin.
Like I said in https://github.com/pulsardev/vue-tour/issues/12 you have to declare the `VTour` component outside of the router view so that it's always accessible. Could you provide us some code?

I'm not sure I understand your last point. What do you mean by "reference a remote component"? You can simply add a link in your last step, even a `router-link`, it should work.
