### ISSUE TITLE
How to add custom css in vue tour

### ISSUE THREAD

**Issue by morshadunnur** [pulsardev/vue-tour#160]
Hello,
I want to add custom CSS in the v-step component. I didn't find any documentation in vue tour wiki.

**Comment by Psychokiller1888** [comment]
The only thing I could override so far is `.v-tour__target--highlighted`

**Comment by HZooly** [comment]
Vue Tour is a light customizable plugin for application tours. You can easily override default CSS rules in your own CSS.

Classes are: `v-step`, `v-step__buttons`, `v-step__content` etc.

See [VStep component sources](https://github.com/pulsardev/vue-tour/blob/master/src/components/VStep.vue)

**Comment by Psychokiller1888** [comment]
Ok, as a reference, because I'm fresh to vue.js, and for others like OP here.... If you are using webpack or vue.js in a modular way, you cannot simple override classes as stated by @HZooly, by using a `<style` tag in your vue.

In your main.js, **after** you import the vuetour css (or any other third party component), you need to import your css file that will override the components classes.

Hope this helps, would have dreamt to find this answer earlier

**Comment by ricky11** [comment]
adding 
`.v-step {
background:white; 
}` 
has no effect, so my guess is that we have to change it in the css file directly?

ths means we can customize v-tour for different parts of the site? it must all use the same styles?
