### ISSUE TITLE
Arrow css position issue

### ISSUE THREAD

**Issue by cain** [pulsardev/vue-tour#199]
**Describe the bug**
The arrow is not positioned correctly.

**Expected behavior**
Arrow be in the middle

**Screenshots**
<img width="1423" alt="Screen Shot 2021-06-09 at 12 26 20 pm" src="https://user-images.githubusercontent.com/15246256/121283282-2f052400-c91e-11eb-8f90-355de33ff990.png">

<img width="587" alt="Screen Shot 2021-06-09 at 12 26 27 pm" src="https://user-images.githubusercontent.com/15246256/121283270-2d3b6080-c91e-11eb-9001-98293917d858.png">

**Desktop (please complete the following information):**
 - OS: ios
 - Browser chrome/safari
 - Version v2

**Comment by cain** [comment]
Sorry for no reproduction link, just saw this upgrading to version 2.

**Comment by mmorainville** [comment]
If it is so after upgrading to v2.x from v1.x, maybe you had some custom CSS set up for v1 and you forgot to update the customization classes?
Otherwise it should be fine with the default CSS.

Popper v2.x changed the default syntax for accessing the direction of the arrow (from `x-placement` to `data-popper-placement`, see https://github.com/pulsardev/vue-tour/commit/ee9da842a48ae29a07e1c8df7b472da5fca7fae3).
