### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by memic84** [pulsardev/vue-tour#81]
Has this project been abandoned? We really like this component, but haven't seen any commits since Oct 2018. Still waiting for some pull request to get merged.

Thanks in advance!

**Comment by DelfsEngineering** [comment]
... or are you interested in letting someone take it over ...

**Comment by mmorainville** [comment]
Hi @memic84,

No it's not abandoned but we're focusing on other projects right now and have very little time to develop new features.
As it is the project is very stable and very customizable so it should fit in the majority of use cases.

We plan to change the delivery process to get the demo out of the project because right now it's a bit cumbersome to release new versions.

We'll think about your proposal to take over the project but right now it's not in our plans.

Thanks for your interest in the project! ;)

**Comment by hc-codersatlas** [comment]
Instead of "taking over", would adding contributors help?

**Comment by mmorainville** [comment]
Indeed we would be more interested in contributors.
But we would be looking for people who have a good experience in maintaining open-source projects and who are already quite familiar with Vue.js and vue-tour.

**Comment by memic84** [comment]
@mmorainville Thanks for the response. I was just curious about the status of the project, not really interested in a take-over :)

Adding contributors seems as a great idea. I will close the issue, because the question has been answered.
