### ISSUE TITLE
Jumping to a step

### ISSUE THREAD

**Issue by Darkzarich** [pulsardev/vue-tour#99]
Is there a way to go to a certain step? Apparently the only way to skip a step is calling `nextStep()` twice...

**Comment by mmorainville** [comment]
Hi @Darkzarich,

Yes you can, it's not documented (yet) but when you create a tour you have access to all its properties, which includes methods like `nextStep` but also internal state (the `data` of the VTour component).

So you can mess with the `currentStep` property. It should do the trick.

**Comment by hriverahdez** [comment]
@mmorainville are you able to jump from the new before UI step functions? I'm trying to validate whether the element is visible and if not skip the step by jumping to the next. I don't know if this is the best approach to solve this problem though, so if you have any suggestions they'd be welcome

**Comment by mmorainville** [comment]
Hi @hriverahdez,

I didn't test that but I don't see why it shouldn't work. So you should be able to do something like (in pseudo-code):

```js
before: type => new Promise((resolve, reject) => {
  // If next target element exists
  // Just resolve the Promise to go to the next step
  resolve()

  // Otherwise, increment the tour currentStep by 2 to skip the step without a target element
  this.$tours['myTour'].currentStep += 2
  // Eventually reject the Promise properly
  reject()
})
```

Please note that you could also do what you want without using the `before` hook at all, just by listening on the `targetNotFound` event which is emitted when... well the target element is not found.
https://github.com/pulsardev/vue-tour/blob/master/src/components/VStep.vue#L120

This way you could increment the `currentStep` in the `$on` callback.

**Comment by hriverahdez** [comment]
Hey, @mmorainville thanks for the quick reply. 

I hadn't seen the `targetNotFound` event in the docs. I already have it working on the before hook though. Still, I wanted to try your approach because it seems more straight forward and also because I'm using the before hook for some other logic (related to interacting with the page before showing the step) and this approach would leave it leaner. However, I'm getting this error:

![image](https://user-images.githubusercontent.com/23222936/87450540-ea361780-c5fe-11ea-8497-aa35d07da72b.png)

It appears to be an issue on [this line](https://github.com/pulsardev/vue-tour/blob/91f65872c8848b3961e9b66350312bfb36c5b0e9/src/components/VStep.vue#L171). I'm simply incrementing the `currentStep` property of the tour, just as suggested above. By the way, for my use case I not only care about whether the element exists in the DOM (a null result from `document.querySelector`) but also if it's visible. This is because sometimes you may have hidden elements due to application business logic, authorization logic, etc. So I went with a helper being used inside the before hook

```
export const validateTargetElemVisible = (target: string) => {
  const el: HTMLElement = document.querySelector(target);

  // if element exists and it's visible
  if (el && el.offsetParent) {
    const style = window.getComputedStyle(el);
    if (style.display !== 'none') {
      return true;
    }
  }

  return false;
};
```

**Comment by mmorainville** [comment]
The error you encounter is "normal" if your target element doesn't exist.
The solution I provided works only if you are sure that the targetElement of the n+2 step exists (so if you want to skip only one target element) and also if there is n+2 steps in your steps array.

So to improve this solution and not encounter this error you could try to check the length of your steps array before incrementing the currentStep (to be sure that that you don't try to target an element for step 6 for exemple if you only have 5 steps).
And to make it work for any step you may have to add a before function which checks the existence of the target element for each step which might not have a target element.

**Comment by Darkzarich** [comment]
@mmorainville 
> Please note that you could also do what you want without using the before hook at all, just by listening on the targetNotFound event which is emitted when... well the target element is not found.

This is what I did as well in my project but not sure if this is got fixed but for me it was throwing a error about element not being found and there is no workaround I found. The problem is I use Sentry.IO and it triggers on every single error in the console so that was... bad moment about this way of solving the issue

**Comment by hriverahdez** [comment]
@mmorainville This was my initial thought, about the step not existing when incrementing the `currentStep`. The problem is that on my test data I have 4 steps and I made sure the second step is the one not found. So, increasing the currentStep by that amount should not throw that error. (I event tried increasing by just 1 in case I was misinterpreting the value). Not only that, the logic I have on the before hook works with this test data by increasing the `currentStep` by 2.

**Comment by hriverahdez** [comment]
Update on this topic

By listening to the `targetNotFound` event I can skip the steps properly as mentioned above by @mmorainville in [his comment](https://github.com/pulsardev/vue-tour/issues/99#issuecomment-658240623). However, the error I stated [above](https://github.com/pulsardev/vue-tour/issues/99#issuecomment-658281247) still shows up when using a custom template for the steps and passing it the  `"highlight"` prop.

The problem is happening in [this line](https://github.com/pulsardev/vue-tour/blob/88d4d72b23d7c5dc82b4d889c9f9ebc58e0d7017/src/components/VStep.vue#L171) when the `removeHighlight` method is called by the `beforeDestroy` hook. Which makes sense, becase the element was not found therefore the `this.targetElement` is null

A possible fix could be null checking before:

```
removeHighlight () {
   if (this.isHighlightEnabled() && this.targetElement) {
     ...
   }
},

**Comment by ricky11** [comment]
How do you go direct to step 2?
